version: "3.2"
services:
  php-fpm:
    build:
      context: ./../../application
      dockerfile: ./infrastructure/docker/php-fpm/Dockerfile
    volumes:
      - type: bind
        source: ./../../application
        target: /var/www/html
  nginx:
    build:
      context: ./../../application
      dockerfile: ./infrastructure/docker/nginx/Dockerfile
    volumes:
      - type: bind
        source: ./../../application
        target: /var/www/html
    ports:
      - "8085:80"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: beguee
      MYSQL_USERNAME: beguee
      MYSQL_PASSWORD: beguee
    ports:
      - "3307:3306"
